### ISSUE TITLE
Access UTM cookies like the old GA universal analytics

### ISSUE THREAD

**Issue by bilbof** [bilbof/purser#1]
Following on from [this HN request](https://news.ycombinator.com/item?id=13679231) to add "the option to follow the same rules that google analytics uses to store UTM cookies."

> Since the release of analytics.js they no longer allow you to ask the ga object what it thinks the current utm variables are (as they can be overwritten, expire, etc). One might want to do this to track stuff in their own database, etc.
> That means one has to attempt to model their algorithm to get it to work, and lets just say thats super annoying: https://lh3.googleusercontent.com/8EiYEKczs9NLsuKkZjRmeygRZ1...

We could add support for interacting with analytics.js & universal analytics. Need more details before work can be started on this.

**Comment by 9mm** [comment]
Yes, this would be great, but you have to keep in mind they do more than just overwrite things according to this flowchart, there are also timeouts involved (6 months if I recall)

I do a lot of analytics tracking where we need to match GA data to analytics stored in a separate database. In order to "link" our GA data to our other metrics we do this based on our millions of UTM campaigns. Because GA doesn't allow us to ask "what UTM variable do you think this is?" we have no single source of truth, and have to imitate it and hope we get it right.

The problem can get a little tricky as you can see here (when also factoring timeouts, etc):

![](https://lh3.googleusercontent.com/8EiYEKczs9NLsuKkZjRmeygRZ1DjP2NWTI5BQ2_3n8iOjfsbb3GjL4ETu241M5gZEOs=w721)

**Comment by bilbof** [comment]
I think this is out of the scope for the library if we're to keep it lightweight. Perhaps this could be added as a plugin / forked version of purser?
